AllCops:
  TargetRubyVersion: 2.3

Naming/FileName:
  Exclude:
    - 'lib/vagrant-trellis-cert.rb'

Metrics/LineLength:
  Max: 143

Metrics/MethodLength:
  Max: 13

Style/Documentation:
  Enabled: false
