AllCops:
  TargetRubyVersion: 2.3

Naming/FileName:
  Exclude:
    - 'lib/vagrant-trellis-cert.rb'

Metrics/AbcSize:
  Max: 18

Metrics/LineLength:
  Max: 156

Metrics/MethodLength:
  Max: 14

Style/Documentation:
  Enabled: false
