AllCops:
  TargetRubyVersion: 2.3

Naming/FileName:
  Exclude:
    - 'lib/vagrant-trellis-cert.rb'

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 12

Style/Documentation:
  Enabled: false
